version: "2"

services:
  app:
    image: simplycodedsoftware/ci:7.4
    volumes:
      - "$PWD:/data/app"
      - "$HOME/.ssh:/home/deploy/.ssh"
    user: 1000:1000
    working_dir: "/data/app"
    command: sleep 99999
    networks:
      - default

networks:
  default:
    driver: bridge